# Lecture2
# Operations

In [2]:
import tensorflow as tf
import os
#tf error message ignore
os.environ['TF_CPP_MIN_LOG_LEVEL']='1'

# visualize it with tensorboard

In [7]:
tf.reset_default_graph()
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

In [8]:
#graph/01
writer = tf.summary.FileWriter('./graphs/01', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
    
writer.close()
#!tensorboard --logdir="./graphs/01" --port 6006

5


In [10]:
#graph/02
tf.reset_default_graph()
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
writer = tf.summary.FileWriter('./graphs/02', tf.get_default_graph())
writer.close()
#!tensorboard --logdir="./graphs/02" --port 6006

# explicitly name them

In [13]:
tf.reset_default_graph()
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a,b, name='add')
writer = tf.summary.FileWriter('./graphs/03', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
writer.close()

5


# Constants

In [16]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='mul')

with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


# tensors filled with a specific value

In [18]:
#shape, dtype, name
a = tf.zeros([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(a))

[[0 0 0]
 [0 0 0]]


In [20]:
#dims, value, name
b = tf.fill([2,3], 8)
with tf.Session() as sess:
    print(sess.run(b))

[[8 8 8]
 [8 8 8]]


# constants as sequences

In [22]:
#start, stop, num, name
a = tf.lin_space(10.0, 13.0, 4)
with tf.Session() as sess:
    print(sess.run(a))

[10. 11. 12. 13.]


# randomly generated constants

In [24]:
#set seed
tf.set_random_seed(1)
#random generate number
a = tf.random_normal([2,3], seed=1)
with tf.Session() as sess:
    print(sess.run(a))

[[ 0.28183395  2.3878284   2.2804048 ]
 [-0.308662   -0.44758153 -0.807146  ]]


# operations

In [26]:
#basic operator
a = tf.constant([2,3], name='a')
b = tf.constant([3,4], name='b')
with tf.Session() as sess:
    print(sess.run(tf.add(a,b)))
    print(sess.run(tf.subtract(a,b)))
    print(sess.run(tf.multiply(a,b)))
    print(sess.run(tf.div(a,b)))
    print(sess.run(tf.divide(a,b)))

[5 7]
[-1 -1]
[ 6 12]
[0 0]
[0.66666667 0.75      ]


# TF vs NP data types

In [28]:
import numpy as np
print(tf.int32 == np.int32)

True


In [30]:
a = tf.zeros([2,3], np.int32)
with tf.Session() as sess:
    print(type(a))
    print(type(sess.run(a)))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


# Variables

In [33]:
#one way, but not recommended
s = tf.Variable(2, name='scalar')
m = tf.Variable([[2,3],[1,2]], name='matrix')
w = tf.Variable(tf.zeros([784,10]))

In [34]:
s = tf.get_variable('scalar', initializer=tf.constant(2))
m = tf.get_variable('matrix', initializer=tf.constant([[1,2],[3,4]]))
w = tf.get_variable('big_matix', shape=[784, 10], initializer=tf.zeros_initializer())

In [38]:
#need to initiate varialbes
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [39]:
# #initilize only a subset of variables
# with tf.Session() as sess:
#     sess.run(tf.variables_initializer([a, b]))

In [48]:
# #initializer a single variable
# w = tf.Variable(tf.zeros[784,10])
# with tf.Session() as sess:
#     sess.run(w.initializer)

# tf.constant vs tf.Variable ??
- constant => an op (method)
- varialbe => class with many ops (class)

# tf.Eval()

In [42]:
w = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w)
    print(len(w.eval()))
    print(w.eval())
    print(w.shape)

<tf.Variable 'Variable_6:0' shape=(700, 10) dtype=float32_ref>
700
[[-0.26150474  0.30394322 -0.56085575 ...  0.57151264  1.4582915
  -1.0479068 ]
 [-1.1494715   0.8708207  -0.7058662  ... -0.00303084 -0.31915438
  -1.627774  ]
 [-0.16629936  1.1293253  -1.9995943  ...  0.8351866   0.10691766
   0.16578136]
 ...
 [ 1.7071378  -1.0033855  -0.3689148  ...  0.14216703 -0.4332929
  -1.0991384 ]
 [-1.6153555   0.5535265   0.300629   ...  0.40379003  0.6065082
  -0.04709903]
 [ 0.6397138   0.968461    0.3651416  ...  0.49500555  0.3197348
  -1.0387429 ]]
(700, 10)


# tf.Variable.assign()

In [48]:
w = tf.Variable(10)
w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())

10


In [49]:
w = tf.Variable(10)
assign_op = w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    sess.run(assign_op)
    print(w.eval())

100


# tf.Variable.assign()

In [60]:
my_var = tf.Variable(2, name='my_var')
my_var_times_two = my_var.assign(2*my_var)
with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two))
    print(sess.run(my_var_times_two))

4
8
16


In [61]:
w = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(w.initializer)
sess2.run(w.initializer)

print(sess1.run(w.assign_add(10)))
print(sess2.run(w.assign_sub(2)))

print(sess1.run(w.assign_add(100)))
print(sess2.run(w.assign_sub(50)))

sess1.close()
sess2.close()

20
8
120
-42


# placeholder
### TF program often has 2phases:
- assemble a graph
- use a session to execute operations in the graph
- **assemble the graph first without knowing the values needed for computation**
- define the funciton f(x,y) = 2*x + y without knowing value of x or y
- x, y are palceholders for the actual values

In [64]:
#create placeholder
a = tf.placeholder(tf.float32, shape=[3])
#create constant
b = tf.constant([5,5,5], tf.float32)
#use placeholder
c = a + b
with tf.Session() as sess:
    print(sess.run(c, {a:[1,2,3]}))

[6. 7. 8.]


In [65]:
# #loop
# with tf.Session() as ses:
#     for a_value in list_of_values_for_a:
#         print(sess.run(c, {a:a_value}))

In [69]:
#create operations, tensors, etc
a = tf.add(2,5)
b = tf.multiply(a, 3)
with tf.Session() as sess:
    #compute the value
    print(sess.run(a))
    print(sess.run(b, feed_dict={a:15}))

7
45


# lazy loading

In [70]:
%%time
#normal loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x,y)

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        print(sess.run(z))
writer.close()

30
30
30
30
30
30
30
30
30
30
CPU times: user 161 ms, sys: 3.98 ms, total: 165 ms
Wall time: 179 ms


In [71]:
%%time
#lazy loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        print(sess.run(tf.add(x,y)))
writer.close()

30
30
30
30
30
30
30
30
30
30
CPU times: user 233 ms, sys: 11.1 ms, total: 244 ms
Wall time: 233 ms
