# Lecture2
# Operations

In [2]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

/home/jk/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [ ]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

with tf.Session() as sess:
    print(sess.run(x))

# visualize it with tensorboard

In [12]:
tf.reset_default_graph()
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

In [13]:
writer = tf.summary.FileWriter('./graphs/01', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))
    
writer.close()
#!tensorboard --logdir="./graphs/01" --port 6006

5


In [14]:
tf.reset_default_graph()
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
writer = tf.summary.FileWriter('./graphs/02', tf.get_default_graph())
writer.close()
#!tensorboard --logdir="./graphs/02" --port 6006

# explicitly name them

In [16]:
tf.reset_default_graph()
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')
writer = tf.summary.FileWriter('./graphs/03', tf.get_default_graph())
with tf.Session() as sess:
	print(sess.run(x)) # >> 5
writer.close()

5


# Constants

In [3]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='mul')

with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


# tensors filled with a specific value

In [6]:
#shape, dtype, name
a = tf.zeros([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(a))

[[0 0 0]
 [0 0 0]]


In [7]:
#dims, value, name
b = tf.fill([2,3], 8)
with tf.Session() as sess:
    print(sess.run(b))

[[8 8 8]
 [8 8 8]]


# constants as sequences

In [9]:
#start, stop, num, name
a = tf.lin_space(10.0, 13.0, 4)
with tf.Session() as sess:
    print(sess.run(a))

[10. 11. 12. 13.]


# randomly generated constants

In [22]:
#set seed
tf.set_random_seed(1)
#random generate number
a = tf.random_normal([2,3], seed=1)
with tf.Session() as sess:
    print(sess.run(a))

[[ 0.28183395  2.3878284   2.2804048 ]
 [-0.308662   -0.44758153 -0.807146  ]]


# operations

In [28]:
a = tf.constant([2,3], name='a')
b = tf.constant([3,4], name='b')
with tf.Session() as sess:
    print(sess.run(tf.add(a,b)))
    print(sess.run(tf.subtract(a,b)))
    print(sess.run(tf.multiply(a,b)))
    print(sess.run(tf.div(a,b)))
    print(sess.run(tf.divide(a,b)))

[5 7]
[-1 -1]
[ 6 12]
[0 0]
[0.66666667 0.75      ]


# TF vs NP data types

In [29]:
import numpy as np
print(tf.int32 == np.int32)

True


In [31]:
a = tf.zeros([2,3], np.int32)
with tf.Session() as sess:
    print(type(a))
    print(type(sess.run(a)))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


# Variables

In [32]:
#one way, but not recommended
s = tf.Variable(2, name='scalar')
m = tf.Variable([[2,3],[1,2]], name='matrix')
w = tf.Variable(tf.zeros([784,10]))

In [33]:
s = tf.get_variable('scalar', initializer=tf.constant(2))
m = tf.get_variable('matrix', initializer=tf.constant([[1,2],[3,4]]))
w = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())

In [34]:
#need to initiate varialbes
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [39]:
# #initilize only a subset of variables
# with tf.Session() as sess:
#     sess.run(tf.variables_initializer([a, b]))

In [48]:
# #initializer a single variable
# w = tf.Variable(tf.zeros[784,10])
# with tf.Session() as sess:
#     sess.run(w.initializer)

# tf.constant vs tf.Variable ??
- constant => an op (method)
- varialbe => class with many ops (class)

# tf.Eval()

In [50]:
w = tf.Variable(tf.truncated_normal([700,10]))
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w)
    print(len(w.eval()))
    print(w.eval())

<tf.Variable 'Variable_4:0' shape=(700, 10) dtype=float32_ref>
700
[[-0.08390216  1.4404938   0.68380797 ...  0.7749831   0.02658102
   1.1418053 ]
 [-0.5850917  -0.26900613  0.7985369  ... -0.46060005 -1.1521726
   1.4177364 ]
 [ 0.76427495  0.23410764  0.43597996 ... -0.88787407 -0.30281684
  -1.8295746 ]
 ...
 [-0.48274234  1.6897753   1.1804852  ... -0.71563464 -1.7230636
   1.3901582 ]
 [ 0.0131304   0.30573937  1.9019264  ... -1.5686415   0.14076976
   1.110402  ]
 [-0.81614155  1.6601014   1.1459519  ...  0.81284183  0.95100576
  -0.29874438]]


# tf.Variable.assign()

In [51]:
w = tf.Variable(10)
w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    print(w.eval())

10


In [52]:
w = tf.Variable(10)
assign_op = w.assign(100)
with tf.Session() as sess:
    sess.run(w.initializer)
    sess.run(assign_op)
    print(w.eval())

100


# tf.Variable.assign()

In [54]:
my_var = tf.Variable(2, name = 'my_var')
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer) #4
    sess.run(my_var_times_two) #8
    sess.run(my_var_times_two) #16

In [58]:
#need to check later
w = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(w.initializer)
sess2.run(w.initializer)

print(sess1.run(w.assign_add(10)))
print(sess1.run(w.assign_sub(2)))

print(sess1.run(w.assign_add(100)))
print(sess1.run(w.assign_sub(50)))

sess1.close()
sess2.close()

20
18
118
68


# placeholder
### TF program often has 2phases:
- assemble a graph
- use a session to execute operations in the graph
- **assemble the graph first without knowing the values needed for computation**
- define the funciton f(x,y) = 2*x + y without knowing value of x or y
- x, y are palceholders for the actual values

In [62]:
#create placeholder
a = tf.placeholder(tf.float32, shape=[3])
#create constant
b = tf.constant([5,5,5], tf.float32)
#use placeholder
c = a + b
with tf.Session() as sess:
    print(sess.run(c, {a:[1,2,3]}))

[6. 7. 8.]


In [64]:
# #loop
# with tf.Session() as ses:
#     for a_value in list_of_values_for_a:
#         print(sess.run(c, {a:a_value}))

In [66]:
#create operations, tensors, etc
a = tf.add(2,5)
b = tf.multiply(a,3)
with tf.Session() as sess:
    #compute the value
    print(sess.run(b, feed_dict={a:15}))

45


# lazy loading

In [68]:
#normal loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x,y)

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        print(sess.run(z))
writer.close()

30
30
30
30
30
30
30
30
30
30


In [69]:
#lazy loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        print(sess.run(tf.add(x,y)))
writer.close()

30
30
30
30
30
30
30
30
30
30
